. ~/.bashrc

export EDITOR=vim
export PATH=$PATH:~/code/bin
export GOPATH=~/code/go
export LC_ALL=en_US.UTF-8
export PS1="\[$(tput bold)\]\[$(tput setaf 1)\]\n \w \n $ \[$(tput sgr0)\]"
export TERM=xterm-256color
export NVIM_TUI_ENABLE_TRUE_COLOR=1

export HISTTIMEFORMAT="%h %d %H:%M:%S> "
export HISTCONTROL=ignoreboth
export HISTSIZE=10000

shopt -s histverify
[[ $- == *i* ]] && stty -ixon

for it in ~/code/autoload/*.sh; do
  . $it
done

eval "$(direnv hook bash)"
