. ~/.bashrc

export EDITOR=vim
export PATH=$PATH:~/code/bin
export HISTFILESIZE=10000
export PS1="\[$(tput bold)\]\[$(tput setaf 1)\]\n \w \n $ \[$(tput sgr0)\]"
# export TERM=xterm-256color

for it in ~/code/autoload/*.sh; do
  . $it
done
