set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'kien/ctrlp.vim'
Plug 'slim-template/vim-slim'
Plug 'bling/vim-airline'
Plug 'altercation/vim-colors-solarized'
Plug 'kchmck/vim-coffee-script'
Plug 'tpope/vim-fugitive'
Plug 'drn/zoomwin-vim'
Plug 'rking/ag.vim'
Plug 'fatih/vim-go'
Plug 'junegunn/vim-easy-align'
Plug 'thoughtbot/vim-rspec'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rails'
call plug#end()

syntax on
filetype plugin indent on

set encoding=utf-8
set nobackup
set noswapfile
set autowriteall
set bh=hide " also enables autowrite for ctrlp

set incsearch
set ignorecase

set mouse=a
set scrolloff=5

set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

" prevent delaying some keybindings (eg, O)
set ttimeoutlen=100

set pastetoggle=<F2>

let NERDTreeAutoDeleteBuffer=1
map <C-n> :NERDTreeToggle<CR>

function! StartUp()
    if 0 == argc()
        NERDTree
    end
endfunction
autocmd VimEnter * call StartUp()

" select last pasted or selected text (with appropriate mode)
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'

let g:airline_powerline_fonts = 1

set t_Co=16
set background=light
colorscheme solarized

let g:go_disable_autoinstall = 1
let g:ctrlp_working_path_mode = 'ra'

" disable ex mode shortcut
nnoremap Q <nop>
" disable man page shortcut
nnoremap K <nop>

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" Rspec shortcuts
map rsf :call RunCurrentSpecFile()<CR>
map rss :call RunNearestSpec()<CR>
map rsl :call RunLastSpec()<CR>

" ctrl-s shortcut to save files
nnoremap <silent> <C-S> :<C-u>confirm write<CR>
inoremap <c-s> <Esc>:confirm write<CR>

" exit shortcut
map <c-q> :qa<CR>
