execute pathogen#infect()
syntax on
filetype plugin indent on

set encoding=utf-8
set nobackup
set autowrite

set incsearch
set ignorecase

set mouse=a
set scrolloff=5

set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

" prevent delaying some keybindings (eg, O)
set ttimeoutlen=100

set pastetoggle=<F2>

let NERDTreeAutoDeleteBuffer=1
map <C-n> :NERDTreeToggle<CR>

function! StartUp()
    if 0 == argc()
        NERDTree
    end
endfunction
autocmd VimEnter * call StartUp()

" select last pasted or selected text (with appropriate mode)
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'
